cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ansible'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'composer'
brew 'ctags'
brew 'docker'
brew 'docker-machine'
brew 'gcc'
brew 'git'
brew 'go'
brew 'groovy'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnupg'
brew 'htop-osx'
brew 'jq'
brew 'libyaml'
brew 'oath-toolkit'
brew 'openssl'
grew 'packer'
brew 'php56'
brew 'php56-apcu'
brew 'python'
brew 'siege'
brew 'vim'
brew 'watch'
brew 'wget'

cask '1password'
cask 'firefox'
cask 'garmin-express'
cask 'google-chrome'
cask 'slack'
