cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'ctags'
brew 'gcc'
brew 'git'
brew 'go'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnupg'
brew 'htop-osx'
brew 'jq'
brew 'libyaml'
brew 'oath-toolkit'
brew 'openssl'
brew 'siege'
brew 'vim'
brew 'watch'
brew 'wget'

cask '1password'
cask 'google-chrome'
cask 'slack'
cask 'Caskroom/cask/spotify'
cask 'Caskroom/cask/iterm2'
cask 'Caskroom/cask/karabiner'
