#!/usr/bin/env python
import json
import os


config_path = os.path.expanduser("~/.karabiner.d/configuration/karabiner.json")

with open(config_path, "r") as f:
    config = json.load(f)

selected = map(lambda x: x["selected"], config["profiles"])

assert selected.count(True) <= 1

if not selected.count(True):
    selected[0] = True
else:
    index = selected.index(True)
    selected[index] = False
    selected[(index + 1) % len(selected)] = True

for index, value in enumerate(selected):
    config["profiles"][index]["selected"] = value

    print "x" if value else " ", config["profiles"][index]["name"]

with open(config_path, "w") as f:
    json.dump(config, f)
